packages:
  - apps/*
  - packages/*

catalog:
  '@elysiajs/eden': 1.4.1
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react-native': 13.3.3
  '@types/react': 19.1.10
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  elysia: 1.4.9
  jsdom: 26.0.0
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.4
  react-native-web: 0.19.13
  react-test-renderer: 19.1.0
  typescript: 5.9.3
  vitest: 3.2.4

nodeLinker: hoisted
