packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

catalog:
  "typescript": 5.9.3
  "react": 19.1.0
  "react-native": 0.81.4
  "@types/react": 19.1.10
  "elysia": 1.4.9
  "@elysiajs/eden": 1.4.1
